"""fix: add aju_banding to usermodel

Revision ID: 0f308ad2ad87
Revises: b785fbd08571
Create Date: 2025-09-24 14:35:36.432204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f308ad2ad87'
down_revision: Union[str, Sequence[str], None] = 'b785fbd08571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
