"""fix hashed_password to hashed_password

Revision ID: 3234c5f3d044
Revises: df9c2b3827df
Create Date: 2025-08-15 11:26:34.171596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3234c5f3d044'
down_revision: Union[str, Sequence[str], None] = 'df9c2b3827df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
