"""rename hashed_password to password

Revision ID: 458ada41951f
Revises: 5a1c11f5c1e4
Create Date: 2025-08-15 11:36:08.901770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458ada41951f'
down_revision: Union[str, Sequence[str], None] = '5a1c11f5c1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('users', 'password', new_column_name='hashed_password')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
