"""add rekening_type column

Revision ID: 9f986d98a9e6
Revises: 02678947808f
Create Date: 2025-09-23 02:57:04.410151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f986d98a9e6'
down_revision: Union[str, Sequence[str], None] = '02678947808f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_forms', sa.Column('rekening_type', sa.Enum('BCA', 'MANDIRI', 'BNI', 'BRI', 'CIMB_NIAGA', 'PERMATA_BANK', 'BANK_DANAMON', name='rekeningtypeenum'), nullable=True))
    op.add_column('insurance_forms', sa.Column('rekening_number', sa.String(), nullable=True))
    op.add_column('insurance_forms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('insurance_forms', 'complaint',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'insurance_forms', ['user_id'])
    op.create_foreign_key(None, 'insurance_forms', 'users', ['user_id'], ['id'])
    op.drop_column('insurance_forms', 'insurance_form')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_forms', sa.Column('insurance_form', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'insurance_forms', type_='foreignkey')
    op.drop_constraint(None, 'insurance_forms', type_='unique')
    op.alter_column('insurance_forms', 'complaint',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('insurance_forms', 'user_id')
    op.drop_column('insurance_forms', 'rekening_number')
    op.drop_column('insurance_forms', 'rekening_type')
    # ### end Alembic commands ###
