"""fix user to document 1toMany

Revision ID: eb7860675034
Revises: 9f986d98a9e6
Create Date: 2025-09-24 06:57:53.137363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7860675034'
down_revision: Union[str, Sequence[str], None] = '9f986d98a9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('insurance_forms_user_id_key'), 'insurance_forms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('insurance_forms_user_id_key'), 'insurance_forms', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
