"""feat: add dokumen_invoice to model

Revision ID: f6cac8a40304
Revises: f831bf79fa4e
Create Date: 2025-09-25 06:21:13.905013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cac8a40304'
down_revision: Union[str, Sequence[str], None] = 'f831bf79fa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aju_bandings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aju_bandings',
    sa.Column('aju_banding_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aju_banding_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('aju_bandings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aju_banding_id', name=op.f('aju_bandings_pkey'))
    )
    # ### end Alembic commands ###
