"""fix: aju_banding to aju_bandings in userModel

Revision ID: f831bf79fa4e
Revises: 1dbe14bfded4
Create Date: 2025-09-24 14:47:32.879146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f831bf79fa4e'
down_revision: Union[str, Sequence[str], None] = '1dbe14bfded4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aju_bandings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aju_bandings',
    sa.Column('aju_banding_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aju_banding_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('aju_bandings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aju_banding_id', name=op.f('aju_bandings_pkey'))
    )
    # ### end Alembic commands ###
