from domain.entities.user import User
from typing import Optional

class UserRepository:
    def get_by_email(self, email: str) -> Optional[User]: ...
    def create(self, user: User) -> User: ...
    def get_by_id(self, id: int) -> Optional[User]: ...